pipeline {
    agent any
   
    environment {
        PATH = "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    }

    stages {
        stage('Compile') {
            steps {
                echo 'Compile code'
                sh 'mvn clean install -DskipTests -f java-demo-app/pom.xml'
            }
        }

        stage('UnitTest') {
            steps {
                echo 'Unit test'
         	sh 'mvn test -f java-demo-app/pom.xml'
            }
	post {
	success {
archiveArtifacts artifacts: '*/*/*.war', followSymlinks: false, onlyIfSuccessful: true
}
}
        }

        stage('SecurityScan') {
            steps {
                echo 'Scan vulnerability'
            }
        }

        stage('QualityGate') {
            steps {
                echo 'QGate'
            }
        }

        stage('BuildApp') {
            steps {
                echo 'Creating docker image'
		sh 'mvn package -f java-demo-app/pom.xml'
            }
        }
        stage('Build docker image') {
    steps {
        echo 'DockerImage'
         sh '''
            /usr/local/bin/docker --version
            /usr/local/bin/docker image build -t gaurav0426/java-app:v1 .
        '''
    }
}
	stage('PushImage') {
            steps {
                echo 'Push image to registry'
            sh '''
            /usr/local/bin/docker push gaurav0426/java-app:v1
	        '''
		}
        }
    }
}

