pipeline {
    agent any
   
    environment {
        PATH = "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    }

    stages {
        stage('Compile') {
            steps {
                echo 'Compile code'
                sh 'mvn clean install -DskipTests -f java-demo-app/pom.xml'
            }
        }

        stage('UnitTest') {
            steps {
                echo 'Unit test'
         	sh 'mvn test -f java-demo-app/pom.xml'
            }
	post {
	success {
archiveArtifacts artifacts: '*/*/*.war', followSymlinks: false, onlyIfSuccessful: true
}
}
        }

        stage('SecurityScan') {
            steps {
                echo 'Scan vulnerability'
            }
        }

        stage('QualityGate') {
            steps {
                echo 'QGate'
            }
        }

        stage('BuildApp') {
            steps {
                echo 'Creating docker image'
		sh 'mvn package -f java-demo-app/pom.xml'
            }
        }
	stage('Build docker image'){
	step {
		echo'DockerImage'
		sh 'docker image build -t registry.local/java-app:v1 .'
}
}
        stage('PushImage') {
            steps {
                echo 'Push image to registry'
            }
        }
    }
}

