pipeline {
    agent any
   
    environment {
        PATH = "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    }

    stages {
        stage('Compile') {
            steps {
                echo 'Compile code'
                sh 'mvn compile Dskip test -f java-demo-app/pom.xml'
            }
        }

        stage('UnitTest') {
            steps {
                echo 'Unit test'
         	sh 'mvn test -f java-demo-app/pom.xml'
            }
        }

        stage('SecurityScan') {
            steps {
                echo 'Scan vulnerability'
            }
        }

        stage('QualityGate') {
            steps {
                echo 'QGate'
            }
        }

        stage('BuildApp') {
            steps {
                echo 'Creating docker image'
		sh 'mvn package -f java-demo-app/pom.xml'
            }
        }

        stage('PushImage') {
            steps {
                echo 'Push image to registry'
            }
        }
    }
}

